Display/Edit audio language (CLI)
MediaArea/MOVMetaEdit pull request #63
Opened 2024-02-27 10:09 UTC by g-maxime

2024-02-27 10:09 UTC, g-maxime commented
Snapshot: https://mediaarea.net/download/snapshots/binary/movmetaedit/20240227/

2024-02-27 11:47 UTC, JeromeMartinez requested changes

2024-02-27 11:47 UTC, JeromeMartinez commented on Source/Common/mp4_Handler.cpp
> +    for (const auto& pair : mp4_mdhd_LanguageMap) {
the list is only if LanguageCode < 0x400, specs:

```
QuickTime stores language codes as unsigned 16-bit fields. All Macintosh language codes have a value that is
less than 0x400 except for the single value 0x7FFF indicating an unspecified language. ISO language codes
are three-character codes, and are stored inside the 16-bit language code field as packed arrays,
[...]
One algorithm for performing this packing is to treat each ISO character as a 16-bit integer. Subtract 0x60 from
the first character and multiply by 2^10 (0x400), subtract 0x60 from the second character and multiply by 2^5
(0x20), subtract 0x60 from the third character, and add the three 16-bit values.
```

So need to convert LanguageCode >= 0x400 to ISO codes
See https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Multiple/File_Mpeg4.cpp#L2986

e.g. instead of showing "9857" it should be displayed "ita".

Actually there is a difference between MOV and MP4, MOV forbids ISO codes for tracks and MP4 forbids Macintosh language codes, but in practice it seems that there is a mix of them, so I suggest:
- If user input is a number, store it as is
- If user input is a 2-letter code, map to Macintosh language codes and error if not found
- If user input is a 3-letter code, ISO language encoding

And similar method for the readout.

2024-02-27 11:47 UTC, JeromeMartinez commented on Source/movedit_main.cpp
> +               || Ztring(argv[argp]) == __T("--languages")))
Accept also "(-)-language", lot of users will use the singular version, I bet.

2024-02-28 11:19 UTC, JeromeMartinez requested changes

2024-02-28 11:19 UTC, JeromeMartinez commented on Source/Common/mp4_Handler.cpp
> +    if (LanguageLabel.size()==3 && isascii(LanguageLabel[0]) && isascii(LanguageLabel[1]) && isascii(LanguageLabel[2]))
`isascii`, try with "it0" ;-).

locale locC("C");
then isalpha(x, locC) && isalpha(x, locC) && isalpha(x, locC)

(or just comparison in order to avoid importing "locale" for only that; no need to accept uppercase)

2024-02-28 14:59 UTC, JeromeMartinez approved these changes

2024-02-28 14:59 UTC, merged